apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devops-java
  labels:
    app: demo-devops-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-devops-java
  template:
    metadata:
      labels:
        app: demo-devops-java
    spec:
      containers:
      - name: demo-devops-java
        image: joshlopez07/demo-devops-java:1.0.0 
        ports:
        - containerPort: 8000
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        livenessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: demo-devops-java
spec:
  type: NodePort
  selector:
    app: demo-devops-java
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30007